# Generated by Django 5.2.16 on 2026-07-11 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardeningRule',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('rationale', models.TextField()),
                ('verification', models.TextField()),
                ('remediation', models.TextField()),
                ('script_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_included_in_script', models.BooleanField(default=True)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='hardening_app.hardeningrule')),
            ],
        ),
    ]
