# Generated by Django 5.2.16 on 2026-07-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardening_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('platform', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('passed_checks', models.TextField()),
                ('failed_checks', models.TextField()),
            ],
        ),
    ]
