# Generated by Django 5.2.16 on 2026-07-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardening_app', '0002_scanreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanreport',
            name='device_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
