# Generated by Django 5.2.16 on 2026-07-13 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardening_app', '0003_scanreport_device_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scanreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardening_app.hardeningrule'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'rule')},
        ),
    ]
